# Generated by Django 5.1.1 on 2024-12-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'UÝJ',
                'verbose_name_plural': 'UÝJ-lar',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('first_year_students', models.IntegerField()),
                ('second_year_students', models.IntegerField()),
                ('third_year_students', models.IntegerField()),
                ('fourth_year_students', models.IntegerField()),
                ('fifth_year_students', models.IntegerField()),
            ],
            options={
                'verbose_name': 'fakultet',
                'verbose_name_plural': 'fakultetler',
            },
        ),
    ]
