# Generated by Django 5.1.1 on 2024-12-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='carousel/')),
            ],
        ),
        migrations.CreateModel(
            name='InfoColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MainPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(max_length=200)),
                ('sub_heading', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='main_page/')),
                ('about_heading', models.CharField(max_length=200)),
                ('about_description', models.CharField(max_length=200)),
                ('carousel_images', models.ManyToManyField(to='UniWeb.carouselimage')),
                ('info_columns', models.ManyToManyField(to='UniWeb.infocolumn')),
            ],
        ),
    ]
