# Generated by Django 5.1.1 on 2024-12-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniWeb', '0003_admissionspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfoColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(max_length=200)),
                ('sub_heading', models.CharField(max_length=200)),
                ('info_columns', models.ManyToManyField(to='UniWeb.infocolumn')),
            ],
        ),
    ]
