# Generated by Django 5.1.1 on 2024-12-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniWeb', '0004_aboutinfocolumn_aboutpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='info_columns',
            field=models.ManyToManyField(to='UniWeb.aboutinfocolumn'),
        ),
    ]
