# Generated by Django 5.1.1 on 2024-12-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniWeb', '0005_alter_aboutpage_info_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfocolumn',
            name='value',
            field=models.CharField(max_length=50),
        ),
    ]
