# Generated by Django 5.1.1 on 2024-12-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniWeb', '0006_alter_aboutinfocolumn_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusFirstInfoColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CampusSecondInfoColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CampusPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_header', models.CharField(max_length=250)),
                ('first_sub_header', models.TextField()),
                ('second_header', models.CharField(max_length=250)),
                ('second_sub_header', models.TextField()),
                ('first_thumb_header', models.CharField(max_length=250)),
                ('first_thumb_sub_header', models.TextField()),
                ('first_thumb_image', models.ImageField(upload_to='campus/')),
                ('second_thumb_header', models.CharField(max_length=250)),
                ('second_thumb_sub_header', models.TextField()),
                ('second_thumb_image', models.ImageField(upload_to='campus/')),
                ('first_info_columns_block', models.ManyToManyField(to='UniWeb.campusfirstinfocolumn')),
                ('second_info_columns_block', models.ManyToManyField(to='UniWeb.campussecondinfocolumn')),
            ],
        ),
    ]
